### ISSUE TITLE
Can't sync destination and monitor

### ISSUE THREAD

**Issue by RyoSanka** [mihirsoni/odfe-monitor-cli#18]
I use EC2 amazon linux to build Opendistro (1.12.0)
I installed odfe-monitor-cli and connect successful with ELK. (Run sync destination and monitor)
But when i check file destination and monitor, it's nothing here.
I check all problem about security but no problem here.
I have created monitor and destination on Kibana.
Pleass give me a advice to resolve.
Thank you.

![hình ảnh_2021-01-30_103225](https://user-images.githubusercontent.com/65341565/106346009-716e8280-62e6-11eb-8d03-8012937c93c1.png)

![hình ảnh_2021-01-30_104025](https://user-images.githubusercontent.com/65341565/106346151-8f88b280-62e7-11eb-946a-0d232f8f0da2.png)

**Comment by marinogiaco** [comment]
I had the same issue in the past, sync destinations doesn't work with latests versions of opendistro-for-elasticsearch, it worked with opendistro-for-elasticsearch:1.4.0

**Comment by marinogiaco** [comment]
The issue is that the query doesn't work with POST:
![Image](https://user-images.githubusercontent.com/55950096/106759868-82472d00-6633-11eb-8810-8beb4d48fa95.png)
If you change to http.MethodGet in [this line](https://github.com/mihirsoni/odfe-monitor-cli/blob/7bf0d36f1d6e0a3aa3d2d778153dc5ec3df64b80/destination/destinations.go#L63) it should work.

**Comment by marinogiaco** [comment]
Got it working with https://github.com/mihirsoni/odfe-monitor-cli/pull/19

**Comment by RyoSanka** [comment]
Thank you. It's work. ^^
